[project]
name = "bench-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "itables>=2.3.0",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
]
