#!/bin/bash
set -Eeuo pipefail
trap 'echo "${0}: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR

script_dir="$(dirname -- "$(realpath -- "${0}")")"
invocation="$(date --iso-8601=seconds)"
bpfwavelet_pcap_bin="${script_dir}/bpfwavelet_pcap"

mkdir -p "${script_dir}/results"

captures=(
	# cobalt-strike.pcap
	# cobalt-strike-filtered.pcap
	# cobalt-strike-filtered-trimmed.pcap
	# heartbleed.pcap
	heartbleed-full.pcap
	# trickbot-a.pcap
	# trickbot-a-filtered.pcap
	# trickbot-a-filtered-trimmed.pcap
	# trickbot-a-filtered-trimmed-further.pcap
	# trickbot-b.pcap
	# trickbot-b-filtered.pcap
	# trickbot-b-filtered-trimmed.pcap
	# trickbot-b-filtered-trimmed-further.pcap
)

parameters='-t 115000000'
for capture in "${captures[@]}"; do
	capture="captures/${capture}"
	outfile="${script_dir}/results/$(basename --suffix=.pcap "${capture}")_$(echo "${parameters}" | tr -d '[:blank:]')_${invocation}"
	errfile="${script_dir}/results/$(basename --suffix=.pcap "${capture}")_$(echo "${parameters}" | tr -d '[:blank:]')_${invocation}.err"
	echo "saving to:"
	echo "${outfile}"
	echo "${errfile}"
	sha256sum "${capture}"

	echo "largest frame: $(tshark -r "${capture}" -T fields -e frame.len | sort -n | tail -1)" >"${errfile}"
	capinfos -u -a -e "${capture}" >>"${errfile}"
	{
		"${bpfwavelet_pcap_bin}" ${parameters} <"${capture}" >"${outfile}" 2>>"${errfile}"
		echo "done with $outfile"
	} &
done

wait
